### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by zakidotai** [ur-whitelab/chemcrow-runs#1]
When I am running the [chromaphore notebook](https://github.com/ur-whitelab/chemcrow-runs/blob/main/chromaphore-rf-369.ipynb), I am getting the following error. I

Note: I have already installed chemcrow

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from chemcrow.evaluation import NoToolsAgent, Evaluator

ModuleNotFoundError: No module named 'chemcrow.evaluation'

**Comment by whitead** [comment]
These notebooks are not meant to be run - they are just archived outputs for the chemcrow paper. See https://github.com/ur-whitelab/chemcrow-public/ for the module.
